# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'RxDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDemo
  pod "RxSwift"
  pod "RxCocoa"
 

  target 'RxDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
